### PR TITLE
Add title, description attributes

### PR DESCRIPTION
**Pull request by cjroebuck**

### CODE REVIEW

**Comment by mcclymont** [comment]
I started to fix it myself also when I realised title wasn't working... then found this PR already exists

**Comment by jhochman** [comment]
You should probably add 'color' in there too ... I needed it for my project and was surprised that it was not included.

**Comment by wlach** [comment]
I created an updated changeset that applies cleanly against master here:

https://github.com/wlach/react-metrics-graphics/commit/aff55931cabc305c6def610de610d60d16398a77

**Comment by wlach** [comment]
I merged that change, closing this:  5bb8865

**Comment by wlach** [comment]
(thanks for the original patch btw!)

**Pull request closed without merging**
